name: Build Project

on:
  push:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # TODO: build sources and javadocJar like in PB
      #- name: Build sources jar
      #  run: ./gradlew sourcesJar

      #- name: Build javadoc jar
      #  run: ./gradlew javadocJar

      - name: Build jars
        run: ./gradlew build

      - name: Upload fabric jar
        uses: actions/upload-artifact@v3
        with:
          name: phobot-fabric-jar
          path: ./fabric/build/libs/phobot-fabric*.jar

      - name: Upload forge jar
        uses: actions/upload-artifact@v3
        with:
          name: phobot-forge-jar
          path: ./forge/build/libs/phobot-forge*.jar

      - name: List uploaded artifacts
        run: |
          echo "Uploaded artifacts:"
          echo "Fabric JAR:"
          ls -l ./fabric/build/libs/phobot-fabric*.jar
          echo "Forge JAR:"
          ls -l ./forge/build/libs/phobot-forge*.jar
